---
#
# Install upgrades and enable unattended upgrades.
#

- name: Upgrade Debian packages
  apt: update_cache=yes upgrade=dist
  register: results

- name: Install Debian utilities
  apt: "name={{ item }} state=present"
  with_items:
    - debconf-utils
    - unattended-upgrades

- name: Enable unattended upgrades
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value=true
  register: results

- name: Reconfigure unattended upgrades
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  when: results | changed
