---
#
# Configure time zones and automatic time updates.
#

- name: Set timezone to Etc/UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/timezone force=yes state=link
  register: result


- name: Reconfigure tzdata
  command: dpkg-reconfigure -f noninterractive tzdata
  when: result | changed


- name: Install NTP daemon
  apt: name=ntp state=present


- name: Start NTP daemon
  service: name=ntp state=started


- name: Set timezone
  timezone:
    name: "Europe/Stockholm"
