language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - mkdir logs
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
