language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements_prod.txt
  - mkdir logs
  - python unitime/manage.py makemigrations
  - python unitime/manage.py migrate

script:
  - python unitime/manage.py test

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://ci.unitime.se/fduexoxsuxhzjskjgqly/
    on_success: always
    on_failure: never
    on_start: never
