language: python

services:
  - redis
  - rabbitmq

env:
  - PYTHON_ENV=travis

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

before_script:
  - celery -A settings worker -l info -B &

script:
  - python manage.py test
