language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements_dev.txt
  - mkdir logs
  - python unitime/manage.py makemigrations
  - python unitime/manage.py migrate

script:
  - python unitime/manage.py test

branches:
  only:
    - master
