# Generated by Django 2.0.1 on 2018-01-17 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0002_course_courseoffering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('teacher', models.CharField(max_length=254)),
                ('room', models.CharField(max_length=254)),
                ('info', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitime.Course')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitime.CourseOffering')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
