# Generated by Django 2.0.1 on 2018-01-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0003_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='info',
        ),
    ]
