# Generated by Django 2.0.1 on 2018-01-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0004_remove_lecture_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='room',
        ),
        migrations.AddField(
            model_name='lecture',
            name='info',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
