# Generated by Django 2.0.1 on 2018-01-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0007_auto_20180117_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseoffering',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'name', 'speed', 'points')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('offering_id', 'registration_id', 'year', 'semester')},
        ),
    ]
