# Generated by Django 2.0.1 on 2018-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0009_auto_20180118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
