# Generated by Django 2.0.1 on 2018-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0010_auto_20180118_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
