# Generated by Django 2.0.1 on 2018-01-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0012_auto_20180118_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('start_datetime', 'end_datetime', 'teacher', 'course', 'course_offering')},
        ),
    ]
