# Generated by Django 2.0.1 on 2018-01-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitime', '0013_auto_20180120_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('start_datetime', 'end_datetime', 'teacher', 'course')},
        ),
    ]
