# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(blank=True, max_length=254)),
                ('name_sv', models.CharField(blank=True, max_length=254)),
                ('syllabus_sv', models.CharField(blank=True, max_length=254)),
                ('syllabus_en', models.CharField(blank=True, max_length=254)),
                ('course_code', models.CharField(max_length=10)),
                ('course_id', models.CharField(blank=True, max_length=15, unique=True)),
                ('course_reg', models.CharField(blank=True, max_length=15, unique=True)),
                ('course_points', models.CharField(default='', max_length=15)),
                ('course_location', models.CharField(default='', max_length=254)),
                ('course_language', models.CharField(default='', max_length=100)),
                ('course_speed', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(max_length=6)),
                ('url', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
