---
#
# Python3
#

- name: Install Python 3
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python-virtualenv
