---
#
# Nginx
#

- name: Install Nginx
  apt: update_cache=yes name="{{ item }}" state=present
  with_items:
    - nginx
    - nginx-full

- name: Start Nginx
  service: name=nginx enabled=yes state=started


- name: Disable Default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Reload Nginx


- name: Copy nginx unitime conf to sites-available
  copy:
      src: unitime
      dest: /etc/nginx/sites-available/unitime


- name: Link unitime to sites-available
  file: src=/etc/nginx/sites-available/unitime
        dest=/etc/nginx/sites-enabled/unitime
        state=link
  notify: Reload Nginx
